### ISSUE TITLE
Correct final files for KneadData

### ISSUE THREAD

**Issue by josenavas** [qiita-spots/qp-shotgun#23]
Currently the plugin is sending the trimmed files back (see [here](https://github.com/qiita-spots/qp-shotgun/blob/master/qp_shotgun/kneaddata/kneaddata.py#L197)) but those files are not the correct ones because they've not been filtered for human data. See [here](https://github.com/tanaes/qp-shotgun/blob/adding-kneaddata-pipeline/qp_shotgun/kneaddata/kneaddata.py#L212) for the actual correct filenames.

**Comment by antgonza** [comment]
KneadData was removed from the requirements. Thus, closing.
