### ISSUE TITLE
Correct call to humann2 with PE reads

### ISSUE THREAD

**Issue by josenavas** [qiita-spots/qp-shotgun#25]
Right now is doing 2 calls, one with the FWD and one with the REV. However, this generates a downstream error. The solution, after discussing with @tanaes and @antgonza the solution would be to add a new parameter ('include-reads' or something better, of type choice with 2 acceptable values: 'all reads', 'forward only').

If 'all reads', concatenates all 4 files from the KneadData output and runs humann2. If 'forward only' concatenates the 2 forward files from KneadData and runs humann2.

**Comment by antgonza** [comment]
We are not using humann2 anymore, closing
