### ISSUE TITLE
Include version string for shogun

### ISSUE THREAD

**Issue by ElDeveloper** [qiita-spots/qp-shotgun#59]
It would be handy if you could see the shogun version in the software list in Qiita:

<img width="496" alt="screen shot 2019-02-07 at 9 11 37 am" src="https://user-images.githubusercontent.com/375307/52429320-ab6e6a80-2ab8-11e9-8eb1-98e6dcb5771f.png">

Currently only Atropos shows the version.

**Comment by antgonza** [comment]
Fixed in master; now:
<img width="405" alt="Screen Shot 2020-01-10 at 6 28 48 AM" src="https://user-images.githubusercontent.com/2014559/72156346-8cd0bd80-3372-11ea-863f-a4fe797d077f.png">
