### ISSUE TITLE
Add kneaddata functionality to plugin

### ISSUE THREAD

**Issue by tanaes** [qiita-spots/qp-shotgun#6]
KneadData plugin should be able to: 
- [x] Accept forward and reverse raw reads
- [x] Screen using trimmomatic for quality and adapter content
- [x] Screen against genome databases to remove host genomic contamination (or PhiX or similar)
- [x] Output trimmed and decontaminated sequences + FastQC reports

**Comment by tanaes** [comment]
commit https://github.com/qiita-spots/qp-shotgun/pull/4/commits/a22922d131f4700db36d39b5d5ee212b8676c6c3 is passing tests with basic functionality (just recovering cleaned forward and reverse reads from basic kneaddata execution). 

Still to do:
- [ ] Add FastQC file output as retained artifacts
- [ ] Add multiple reference db support
- [ ] Add MultiQC summary of FastQC output

**Comment by tanaes** [comment]
Per conversation with @josenavas, the QC options are going to get rolled in to artifact validation.

**Comment by antgonza** [comment]
KneadData was removed from the requirements. Thus, closing.
